#!/bin/bash

MYIP=$(wget -qO- ipv4.icanhazip.com)

	clear
  
	
	cname=$( awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo )
	cores=$( awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo )
	freq=$( awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo )
	tram=$( free -m | awk 'NR==2 {print $2}' )
	swap=$( free -m | awk 'NR==4 {print $2}' )
	up=$(uptime|awk '{ $1=$2=$(NF-6)=$(NF-5)=$(NF-4)=$(NF-3)=$(NF-2)=$(NF-1)=$NF=""; print }')

  echo "=============== Welcome To Server======= - IP: $MYIP ==============="
	echo "===============AutoscriptByOrangKuatSabahanTerkini=================="
	echo -e "\e[032;1mCPU model:\e[0m $cname"
	echo -e "\e[032;1mNumber of cores:\e[0m $cores"
	echo -e "\e[032;1mCPU frequency:\e[0m $freq MHz"
	echo -e "\e[032;1mTotal amount of ram:\e[0m $tram MB"
	echo -e "\e[032;1mTotal amount of swap:\e[0m $swap MB"
	echo -e "\e[032;1mSystem uptime:\e[0m $up"
	echo "------------------------------------------------------------------------------"
	echo "Sila pilih pilihan dibawah ini"
	echo -e "\e[031;1m 1\e[0m) "\e[032;1mBuat Akaun SSH/OpenVPN (\e[035;1muser-add\e[0m)"
	echo -e "\e[031;1m 2\e[0m) "\e[032;1mGenerate Akaun SSH/OpenVPN (\e[035;1muser-gen\e[0m)"
	echo -e "\e[031;1m 3\e[0m) "\e[032;1mGanti Password Akaun SSH/OpenVPN (\e[035;1muser-pass\e[0m)"
	echo -e "\e[031;1m 4\e[0m) "\e[032;1mTambah Masa Aktif Akaun SSH/OpenVPN (\e[035;1muser-renew\e[0m)"
	echo -e "\e[031;1m 5\e[0m) "\e[032;1mHapus Akaun SSH/OpenVPN (\e[035;1muser-del\e[0m)"
	echo -e "\e[031;1m 6\e[0m) "\e[032;1Buat Akaun PPTP VPN (\e[035;1muser-add-pptp\e[0m)"
	echo -e "\e[031;1m 7\e[0m) "\e[032;1mMonitoring Dropbear (\e[035;1mdropmon [PORT]\e[0m)"
	echo -e "\e[031;1m 8\e[0m) "\e[032;1mCheck Login Dropbear, OpenSSH, PPTP VPN dan OpenVPN (\e[035;1muser-login\e[0m)"
	echo -e "\e[031;1m 9\e[0m) "\e[032;1mKill Multi Login Manual (1-2 Login) (\e[035;1muser-limit [x]\e[0m)"
	echo -e "\e[031;1m10\e[0m) "\e[031;1mDaftar Akaun dan Expire Date (\e[035;1muser-list\e[0m)"
	echo -e "\e[031;1m11\e[0m) "\e[031;1mDaftar Akaun Aktif (\e[035;1muser-active-list\e[0m)"
	echo -e "\e[031;1m12\e[0m) "\e[031;1mDaftar Akaun Expired (\e[035;1muser-expire-list\e[0m)"
	echo -e "\e[031;1m13\e[0m) "\e[031;1mDisable Akaun Expired (\e[035;1mdisable-user-expire\e[0m)"
	echo -e "\e[031;1m14\e[0m) "\e[031;1mDelete Akaun Expired (\e[035;1mdelete-user-expire\e[0m)"
	echo -e "\e[031;1m15\e[0m) "\e[031;1mBanned Akaun (\e[035;1mbanned-user\e[0m)"
	echo -e "\e[031;1m16\e[0m) "\e[031;1mRestart Dropbear (\e[035;1re-drop\e[0m)"
  echo -e "\e[031;1m17\e[0m) "\e[031;1mRestart OpenSSH (\e[035;1service ssh restart\e[0m)"
	echo -e "\e[031;1m18\e[0m) "\e[031;1mMemory Usage (\e[035;1mps-mem\e[0m)"
	echo -e "\e[031;1m19\e[0m) "\e[031;1mSpeedtest (\e[035;1mtest-speed\e[0m)"
	echo -e "\e[031;1m20\e[0m) "\e[031;1mBenchmark (\e[035;1mbenchmark\e[0m)"
	echo -e "\e[031;1m21\e[0m) "\e[031;1mReboot Server (\e[035;1mreboot\e[0m)"
	echo ""
	echo -e "\e[031;1m x\e[0m) Exit"
	echo ""
	read -p "Masukkan pilihan [1-20], kemudian tekan ENTER: " option1
	case $option1 in
		1)
		clear
		user-add
		exit
		;;
		2)
		clear
		user-gen
		exit
		;;
		3)
		clear
		user-pass
		exit
		;;
		4)
		clear
		user-renew
		exit
		;;
		5)
		clear
		user-del
		exit
		;;
		6)
		clear
		user-add-pptp
		exit
		;;
		7)
		clear
		read -p "Isikan Port Dropbear yang akan dimonitor: " PORT
		dropmon $PORT
		exit
		;;
		8)
		clear
		user-login
		exit
		;;
		9)
		clear
		read -p "Isikan Maximal Login (1-2): " MULTILOGIN
		user-limit $MULTILOGIN
		exit
		;;
		10)
		clear
		user-list
		exit
		;;
		11)
		clear
		user-active-list
		exit
		;;
		12)
		clear
		user-expire-list
		exit
		;;
		13)
		clear
		disable-user-expire
		exit
		;;
		14)
		clear
		delete-user-expire
		exit
		;;
		15)
		clear
		banned-user
		exit
		;;
		16)
		clear
		service dropbear restart
		exit
    ;;
    clear
    Restart OpenSSH
    exit
		;;
		18)
		clear
		ps-mem
		exit
		;;
		19)
		clear
		test-speed
		exit
		;;
		20)
		clear
		benchmark
		exit
		;;
		21)
		clear
		reboot
		exit
		;;
		x)
		clear
		exit
		;;
	esac
done

cd ~/
rm -f /root/IP
